project_id = "etslsnlmexokwvrneomd"

[functions.send-outing-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.extract-coordinates]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false